name: CI & CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: toor
          POSTGRES_USER: root
          POSTGRES_DB: yapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npx prisma db push && npx jest --runInBand
        env:
          DATABASE_USER: root
          NODE_ENV: test
          TZ: Etc/Universal
          DATABASE_URL: postgresql://root:toor@localhost:5432/yapi?schema=public

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: SSH deploy
        run: |
          ./bin/deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER_HOST: ${{ secrets.SSH_USER_HOST }}
